sudo: required
services:
  - docker

before_install:
  - docker build -t jorantes/docker-react -f Dockerfile.dev .

script: 
  - docker run jorantes/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-2-600919279186
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secure_access_key:
    secure: "$AWS_SECRET_KEY"
